theme: jekyll-theme-cayman #主题

# 设置 Site.*
lang: zh_CN     #HTML语言
title: hi Blog                     #你博客的标题
#SEOTitle: 你的博客 | Your Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
#email: You@gmail.com    
description: "desc Blog"              #网站介绍
keyword: "boot ipxe" #关键词
url: "https://boot.ikwb.com"          # 这个就是填写你的博客地址 sitemap用
#baseurl: ""      # 这个我们不用填写
#show_downloads: "false" # 显示下载

#sidebar: true                           # 是否开启侧边栏.
#sidebar-about-description: "介绍的话。。。"

defaults:
  -
    scope:
      path: "test.md"
    values:
      layout: null


plugins:
  - jekyll-sitemap #搜索地图
  - jekyll-mentions # 用户链接@
  - jekyll-redirect-from #重定向
